VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsCoachDay"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public key_srep As String
Public cdDateStat As Date
Public cdDateCoaching As Date
Public BrandStat As String
Public person As String
Public shef As String
Public visitedTotalCLNs As Integer
Public visitedCnqCLNs As Integer
Public orders As Integer
Public step1 As Integer
Public step2 As Integer
Public step3 As Integer
Public step4 As Integer
Public step5 As Integer
Public step6 As Integer
Public step7 As Integer
Public comment As String
