VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsKPI"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Explicit

Public cdDateStat As Date
Public BrandStat As String
Public PersonName As String
Public WDays As Long
Public TargetCA As Long
Public OrdersSLN As Long
Public OrdersPhone As Long
Public Visits2Act As Long
Public VisitedAct As Long
Public Visits2cnq As Long
Public VisitedCnq As Long






                
