VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsKPI"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Explicit

Publib cdDateStat as Date
Publib nm_brand as String 
Publib nm_Srep as String
Publib num_target_CA as Long 
Publib num_orders_SLN as Long
Publib num_orders_phone as Long
Publib num_visits2act as Long
Publib num_visited_act as Long
Publib num_visits2cnq as Long
Publib num_visited_cnq as Long






                